# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cryptocurrencyTracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cryptocurrencyTracker

  target 'cryptocurrencyTracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cryptocurrencyTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'cryptocurrencyTracker-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cryptocurrencyTracker-tvOS

  #target 'cryptocurrencyTracker-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

end
